### ISSUE TITLE
Can't add images via PHP

### ISSUE THREAD

**Issue by lucaroehrl** [Knawat/featured-image-by-url#10]
Hey guys,

is there a pre-build function to add images via PHP?
Just adding images URLs to the database is clearly not working.
I can't figure out how to insert the Featured Image or Gallery URLs to this special WooCommerce-scheme :cry:

**Comment by iamdharmesh** [comment]
Hello @Screenload, 

Thanks for reaching out.

WooCommerce needs image width and height for display image in lightbox. so we are storing it with image URLs. but you can import only image URL string into featured image field and comma-separated image URLs for the gallery fields. the plugin will take care of all other things.

hope this will help you.

Thanks,
Dharmesh Patel

**Comment by iamdharmesh** [comment]
Hello @Screenload,

Feel free to open this issue if you need any more information regarding this.

Thanks
