### ISSUE TITLE
Does this override the has_post_thumbnail() or set_post_thumbnail()

### ISSUE THREAD

**Issue by kryztoval** [Knawat/featured-image-by-url#11]
I have a few hooks that use those functions to generate the featured image and I am wondering if I can use the same hooks to send the code to insert things in the functions.php in the theme. Can I use that or should i use another function to check if it has a thumbnail?

**Comment by iamdharmesh** [comment]
Hello @kryztoval, 

Thanks for reaching out and sorry for the delayed response.

Yes this plugin is override `has_post_thumbnail()` function if featured image by URL is added for particular post. So, you can use this function for check if it has a thumbnail or not.

Let us know if you need any other help.

Thanks,
Dharmesh

**Comment by kryztoval** [comment]
Perfect, it worked like a charm. 

I made a hook on the functions.php and now every single post gets the thumbnail even if it has no images from the library. Amazing job!
