### ISSUE TITLE
Disable post type "post" also disables post type "product"

### ISSUE THREAD

**Issue by EdithAllison** [Knawat/featured-image-by-url#12]
In Settings, ticking disable "post" also disables "product" for WooCommerce. 
Happened on Multisite with WooCommerce plugin. 
Unticking "post" fixes the issue.

**Comment by iamdharmesh** [comment]
Hello @EdithAllison,

Thanks for creating issue and sorry for the late response.

We have tried to reproduce issue you are facing but we are not able to reproduce it.

Let us know if you still facing this issue. 

Thanks,
Dharmesh Patel

**Comment by EdithAllison** [comment]
I'm sorry but we've decided to go with a different solution so I don't currently have access to a test environment for your plugin. I assume as product is a post type, disabling post disables all post types? If you can't reproduce, please close. Thank you.

**Comment by iamdharmesh** [comment]
@EdithAllison, Thanks for your response.
