### ISSUE TITLE
How to Upload Featured Image Url and Product Gallery Image Url Using CSV file 

### ISSUE THREAD

**Issue by nitanshrastogi** [Knawat/featured-image-by-url#15]

**Comment by iamdharmesh** [comment]
Hello @nitanshrastogi,

Yes you can add external images to featured image and Product Gallery via WooCoomerce Product CSV import. for that you have to pass image urls into meta_data fields. Please find meta_key for meta data below.

**Product Featured Image**: _knawatfibu_url
**Product Gallery Images**: _knawatfibu_wcgallary (comma separate image Urls for multiple images)
**Product Variation Image**: _knawatfibu_url

Hope this will help you.

Thanks,
Dharmesh

**Comment by iamdharmesh** [comment]
@nitanshrastogi, Feel free for re-open this issue if you still have any doubts in this.
