### ISSUE TITLE
Resized image is static

### ISSUE THREAD

**Issue by falon** [Knawat/featured-image-by-url#17]
Hello,
 I checked `Display Resized Images` to avoid big image to show under some context (in Service list).
I have an image by url which changes very frequently. The image url is always the same, but the content updates frequently, once 10 minutes. If I check `Display Resized Images` a static thumbnail cache is created forever.
Is there a way to dynamically change the resized image accordingly when the main feature image changes?

**Comment by iamdharmesh** [comment]
Hello @falon,

Thanks for creating issue.

We have added support for JetPack photon for `Display Resized Images` on the fly. and unfortunately photon CDN is heavily cached and it doesn't allow us to clear it. 

So, we can't change a resized image at photon CDN, unless we change the image name. If image name is different every time then it can be different.

Thanks,
Dharmesh Patel
