### ISSUE TITLE
Add image URL to product variation

### ISSUE THREAD

**Issue by eugeniojauregui** [Knawat/featured-image-by-url#2]
Hi! 

Great plugin! It save me a lot of time!

I got a doubt about how to associate an image url to a product variation.

When I edit the featured image of the variation the button prompt the wordpress media uploader, but i don't found the field to insert the URL.

Thanks!

![image](https://user-images.githubusercontent.com/1844455/37544556-1e1fc834-2944-11e8-9cf2-b5ec1304e3b2.png)

**Comment by iamdharmesh** [comment]
Hello @eugeniojauregui,

Thanks for reaching out to us and create issue. 

You can add image to product variation using "**Product Variation Image by URL**" please check below screenshot for more information. 

![product_variation_support](https://user-images.githubusercontent.com/10613171/37586791-55077672-2b55-11e8-8c86-f9a0d21b7442.png)

We have added it as a separate field for keep default featured image support also. so user can set featured image by default field or by URL field. 

**Please note: We haven't released this Product variation support to our plugin on WP.org. so you can get it by clone master branch of this repository. we will release it soon in our upcoming release.** 

Feel free to ask us if you have any difficulties. 

Thanks & Regards, 
Knawat Team

**Comment by eugeniojauregui** [comment]
Hi Dharmesh!
Thanks for your anwers!
Yes, yersterday late I realized that i was using the WP.org version of the plugin, so I get the GitHub version and it works.
Thanks again!
