### ISSUE TITLE
Shopz.io support

### ISSUE THREAD

**Issue by HazemKhaled** [Knawat/featured-image-by-url#20]
The plugin not working with Shopz.io, everything else working except images

![img_6d8125972194-1](https://user-images.githubusercontent.com/125433/51985883-05b36e00-24b0-11e9-98fe-4c34826b77bd.jpeg)

**Comment by iamdharmesh** [comment]
Related to #13

**Comment by HazemKhaled** [comment]
It looks fixed, can we close this? what about #13, is it solved now?

**Comment by HazemKhaled** [comment]
It looks solved, thanks

@dharmeshtatva what about #13, can we close it also?

**Comment by HazemKhaled** [comment]
@dharmeshtatva is this the same issue here #13 ? can we close it?
