### ISSUE TITLE
Product images not appearing, Placeholder only.

### ISSUE THREAD

**Issue by Greyrocket** [Knawat/featured-image-by-url#22]
Website is RocketRoseArt.com. Theme is the Woocommerce Storefront theme.
After a recent update, I think, images stopped appearing and all I see is the placeholder image.
Deactivated and reactivated. No change. Checked links and they are fine.
Products are now inactive as they don't look very professional without an image.

**Comment by aliaus** [comment]
I have the same issue with Woocommerce last version.
the image in page shop and on the single page doesn't show up.
very bad if plugins cant fast update.
1 star

**Comment by awheeler826** [comment]
I have the same issue, please help
