### ISSUE TITLE
Not changing featured image when changing color

### ISSUE THREAD

**Issue by jpstarr94** [Knawat/featured-image-by-url#29]
When a user selects a different color on a WooCommerce Product the image does not change. 

You can see an example here: https://probitasstore.com/minnkota/product/taryn/

You can see an example of how it should work here: https://probitasstore.com/altru/product/port-authority-ladies-collective-outer-shell-jacket/

What would I need to change or is there a compatibility issue with the new update of Wordpress/WooCommerce?

**Comment by jpstarr94** [comment]
Following up on this...

**Comment by Super-Saiyan-Mohamed** [comment]
Hello @jpstarr94,
We didn't test our plugin with the latest Woocommerce version but, if you want to customize the plugin for your case you can change the function `knawatfibu_overwrite_thumbnail_with_url` in class `Featured_Image_By_URL_Common`. We will add this issue to the workflow and work on it soon. Sorry for the late response.

**Comment by phamquocthinh** [comment]
Hi @jpstarr94 do you have the answer for this problem? If yes, please give me an advice :D

**Comment by iamdharmesh** [comment]
Resolved with last release. feel free to open if you still facing it.
