### ISSUE TITLE
$pid is not defined

### ISSUE THREAD

**Issue by Johntaa** [Knawat/featured-image-by-url#3]
https://github.com/Knawat/featured-image-by-url/blob/dc161ae5f45187d3357c4a1e43edc0ea76f3ecb5/includes/class-featured-image-by-url-admin.php#L149

I think $pid should be changed to $post_id

**Comment by iamdharmesh** [comment]
Hello @Johntaa, 

Thanks a lot for note and report issue. Issue has been fixed and we will release it soon in our upcoming release v1.1.0. till that you can use master branch of this repo.

Thanks,
Dharmesh
