### ISSUE TITLE
Image from URL for WooCommerce Product variation - Does not Work

### ISSUE THREAD

**Issue by tareq021** [Knawat/featured-image-by-url#33]
Copying image url on Product Variation Image gets the image on admin panel right. But, at the client side, on product detail page the variation images does not show.

**Comment by Super-Saiyan-Mohamed** [comment]
Hello,
Can You please specify the steps You made to generate this issue? Thank You.
Regards.

**Comment by tareq021** [comment]
Hello,
Please see the attached images.

**Adding image url in product variation section**

![Image_set_in_Variation](https://user-images.githubusercontent.com/13526235/78555258-754c8800-782e-11ea-878f-be4a47f446a4.PNG)

**The added image is not shown in product details page**

![Product_details_page](https://user-images.githubusercontent.com/13526235/78555272-7f6e8680-782e-11ea-9b99-a9b0d658a764.PNG)

**Comment by Super-Saiyan-Mohamed** [comment]
@tareq021 Thank You for the issue steps, I will try to regenerate it and fix it soon. Have a great day.

**Comment by tareq021** [comment]
@hamusthekiller You are welcome. This will really help a lot.

**Comment by jpstarr94** [comment]
Is this fixed? I am running into the problem here still: http://probitasstore.com/valleyseniorliving/product/port-authority-ultra-plush-blanket/

I am updated to latest wordpress and woocommerce and featured image URL plugin

**Comment by Super-Saiyan-Mohamed** [comment]
Hello @jpstarr94,

I'm sorry We are late on fixing this issue but We will fix it and deploy it as soon as possible.

Stay safe and have a great day.

**Comment by iamdharmesh** [comment]
Already fixed. feel free to open if you still face it.
