### ISSUE TITLE
Not showing woocommerce product image.

### ISSUE THREAD

**Issue by midriffdeveloper7** [Knawat/featured-image-by-url#35]
Hello dear, plugin is not showing the woocommerce product images please fix it.

**Comment by Super-Saiyan-Mohamed** [comment]
Hello @midriffdeveloper7,
Can You specify the issue more or give me test steps? Is the issue related to the new WP 5.4 or something else?
Have a great day.

**Comment by midriffdeveloper7** [comment]
The this issue is in latest wp. Custom url image is not showing in shop pages...

**Comment by Super-Saiyan-Mohamed** [comment]
Hello @midriffdeveloper7,
We uploaded a new version. Please update your current version and the problem should be fixed.
Regards.

**Comment by midriffdeveloper7** [comment]
Ok thanks dear

**Comment by Super-Saiyan-Mohamed** [comment]
@midriffdeveloper7 I will close the issue for now but, if any problem comes up regarding the same issue feel free to re-open it again.
Have a great day.
