### ISSUE TITLE
Variation Image Not showing

### ISSUE THREAD

**Issue by jpstarr94** [Knawat/featured-image-by-url#36]
The variation image is not showing. When I go to the product the featured image shows, but when I click on a variation the featured image continues to be shown. On the example from the link below, the "Black/White Plaid" option will work as I setup an actual image for that option just to show that it would work when you did it the default way. When using the plugin way (by URL) it does not work. 

Link: http://probitasstore.com/valleyseniorliving/product/port-authority-ultra-plush-blanket/

**Comment by jpstarr94** [comment]
Is there any update on this? I had to revert back to woocommerce version 3.8.1 in order to get it to work for the time being. Please help!

**Comment by Super-Saiyan-Mohamed** [comment]
Hello @jpstarr94,

I'm sorry for getting back late to You. I will re-generate the issue and try to solve it as soon as possible.

Stay safe.

**Comment by jpstarr94** [comment]
If there is anything you need from just let me know.

**Comment by jpstarr94** [comment]
Is there an update on this?

**Comment by Super-Saiyan-Mohamed** [comment]
Hello @jpstarr94,

We are still working on this issue and will reply as soon as possible with an update or a new version.

Stay safe.

**Comment by jpstarr94** [comment]
Is there any update? I was under the impression that this would soon be fixed.

**Comment by Super-Saiyan-Mohamed** [comment]
Hello @jpstarr94,
We are sorry for being late in our fix but, We will fix it soon.
Best Regards.

**Comment by jpstarr94** [comment]
@hamusthekiller  Our plugins are no longer supporting the version of WooCommerce we are on because we cannot update WooCommerce due to the plugin not working with the newer version of WooCommerce. This is frustrating. If I paid you would you be able to get it done this week?

**Comment by jpstarr94** [comment]
Any update? This has been a problem since April...

**Comment by iamdharmesh** [comment]
Hello @jpstarr94, 

Sorry for late update. I have created PR for fix this issue. https://github.com/Knawat/featured-image-by-url/pull/40
It will get released soon.

So, for now you can download and use plugin from here. 
https://github.com/iamdharmesh/featured-image-by-url/archive/variation-support.zip

Let me know if issue persist.

Thanks.

**Comment by jpstarr94** [comment]
Thanks so much!!

**Comment by iamdharmesh** [comment]
Closing as its already resolved.
