### ISSUE TITLE
variation images?

### ISSUE THREAD

**Issue by wyatt121** [Knawat/featured-image-by-url#5]
Hi

Any plans to add functionality to allow external images for variations?

Any help is much appreciated.  

Wyatt

**Comment by iamdharmesh** [comment]
Hello @wyatt121,

Yes, we already added functionality to allow external images for variations. and we will release it in upcoming version soon. So, for now please use master of this repository.

Thanks.

**Comment by iamdharmesh** [comment]
Hello @wyatt121,

We have released latest version of this plugin with functionality to allow external images for variations. So, now you can directly upload it from your website. 

Also, Feel free to report if you have any issue with this plugin.

Thanks,
Dharmesh Patel

**Comment by wyatt121** [comment]
Hi Dharmesh,

This is great news!  One more question if you don't mind.  Can I add external image urls to both the featured image and variation image fields via the WooCommerce REST API?   This is my goal...  I have thousands of products to add w/ variations, and all my products have their images on an external image server.

Any help is much appreciated.

Wyatt

**Comment by iamdharmesh** [comment]
Hello Wyatt,

Yes you can add external images to featured image and variation image via WC REST API.

You can pass Image URL to meta data for set it as a Featured image or variation image please find meta_key for meta data below.

**Product Featured Image:**  _knawatfibu_url
**Product Gallery Images:**   _knawatfibu_wcgallary (comma separate image Urls for multiple images)
**Product Variation Image:**  _knawatfibu_url

Hope this will help you.

Thanks,
Dharmesh

**Comment by wyatt121** [comment]
Hi Dharmesh,

You rock!  I installed the plugin on my website.  And it works perfectly.  You are a lifesaver!  I'm now testing the API functionality.  Will report back soon.  I can't thank you enough.  

Wyatt

**Comment by wyatt121** [comment]
Hi Dharmesh,

I was able to get your plugin to work on the API perfectly!  No issues.  

I think I may have found a bug...  It does not appear that the ALT tag for the featured image is being displayed on the front end.  It saves just fine but does not show on the product image.  

Also, do you plan on including an ALT tag for the variation images?

Keep up the great work!

Thanks Again!

Wyatt

**Comment by iamdharmesh** [comment]
Hello @wyatt121, 

Glad to know that plugin worked fine for you.

Thanks for report issue on ALT tag for featured image and new feature request (ALT tag for variation), I am adding this to my TO DO list for fix this in future release.

Let me know if I can help you in any other difficulties.

Also, I would appreciate if you can post review about plugin [here](https://wordpress.org/support/plugin/featured-image-by-url/reviews/#new-post). It will help people to find out more about this plugin.

Warm Regards, 
Dharmesh

**Comment by wyatt121** [comment]
Hi Dharmesh,

I'm very happy to leave a great review.  I have found 2 new bugs.  I'm unsure if it's your plugin or I need to make a change in my theme.  I use the popular Flatsome.  Here are the issues.

1.  When I add a product to the cart, the external featured image does not load.

2.  When I add a product to the cart, the external image within the cart does not load.

See attached screenshots.

Any help is much appreciated.

Wyatt
![after_adding_to_cart](https://user-images.githubusercontent.com/17152395/39017444-2addfd9e-43d8-11e8-8b41-4fd6ece4c168.png)
![before_add_to_cart](https://user-images.githubusercontent.com/17152395/39017446-2b04a4e4-43d8-11e8-8c43-4c0ada4b0900.png)

**Comment by iamdharmesh** [comment]
Hello Wyatt, 

Thanks for your kind review.

Please find comments on your issue below.

**1.) When I add a product to the cart, the external featured image does not load.**
==> Its working fine here also it should work file at your end, as per your setup add-to-cart is reloading page so image is also re-load please wait some time for check image will load.. implement browser cache will help in this case. (if you check in your screenshot upper part of image loaded)

**2.) When I add a product to the cart, the external image within the cart does not load.**
==> Its issue of your image CDN its doesn't deliver images over https://. cart product image url is '//img2.hometownapparel.com/images/TS-P002-M-GR-D001-LT002-BL.jpg' and your site is over https:// so image will load over https:// but you CDN network doesn't deliver images over https:// so issue has been happen.. please add SSL on your CDN server.

Thanks,
Dharmesh
